#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' #no color
if [[ "$2" == "-o" ]]; then
	out_folder="$3"
else
	out_folder=./bin/
	if ! [ -e "$out_folder" ]; then
		echo dirrectory "$out_folder" does not exist
		echo please create this directory or edit "$0"
		exit 0
	fi
	out_folder=./bin/"$1"
fi

g++ "$1".cpp -Wall -Wextra -Werror -pedantic -std=c++20 -o "$out_folder"

is_compiled=$?
if [ "$is_compiled" != "0" ]; then
	echo -e compilation ${RED}failed${NC}[${RED}-${NC}]
	exit 0
fi
echo -e compiled ${GREEN}successfully${NC}[${GREEN}+${NC}]

if [[ "$2" == "r" || "$4" == "r" ]]; then
	./"$out_folder"
	echo
fi
